# Server configurations
server:
  host: "localhost"
  port: "8000"
  timeout: 15 # secs

# Database credentials
# Database Username and Password
# Set env var: MONGO_USERNAME
# Set env var: MONGO_PASSWORD
database:
  host: "localhost"
  port: 27017

# JWT Secret
#  Set env var: JWT_SECRET
crypto:
  issuer: "RPJ Auth Service"
  tokenExpire: 15 # mins
  SSLCert: "./crypto/cert.pem"
  SSLKey: "./crypto/key.pem"



